#!/usr/bin/env php
<?php
if (count($argv) < 2) {
    echo 'Usage:' . PHP_EOL;
    echo sprintf('    %s controllerName [moduleName]', $argv[0]) . PHP_EOL;
    exit(PHP_EOL);
}

$controller = $argv[1];
$module = $argv[2] ?? 'shlink';

// Change current dir to project root
$gitRoot = exec('GIT_EDITOR=echo git config -e');
$parts = explode('/', $gitRoot);
array_pop($parts);
$gitRoot = implode('/', $parts);
chdir($gitRoot . '/..');

// Read controller template
$controllerTemplate = file_get_contents('scripts/templates/controller-template.txt');
$content = str_replace('%controller%', $controller, $controllerTemplate);
$content = str_replace('%module%', $module, $content);

// Create controller file
$controllerFile = sprintf('app/js/controllers/%s.js', $controller);
file_put_contents($controllerFile, $content);

// Add controller to index.html
$lines = explode(PHP_EOL, file_get_contents('app/index.html'));
$length = count($lines);
$lastLines = [
    $lines[$length - 4],
    $lines[$length - 3],
    $lines[$length - 2],
    $lines[$length - 1],
];
foreach ($lines as $i => $line) {
    if ($i === $length - 4) {
        $lines[$i] = sprintf('        <script src="/js/controllers/%s.js"></script>', $controller);
    } elseif ($i > $length - 4) {
        unset($lines[$i]);
    }
}
$lines = array_merge($lines, $lastLines);
file_put_contents('app/index.html', implode(PHP_EOL, $lines));

// TODO Add controller to Gruntfile
